version: "3.9"

networks:
  net:
    driver: bridge

services:
  cargo_db:
    container_name: CargoDb
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 2s
      retries: 2
    networks:
      - net

  cargo_app:
    container_name: CargoApp
    build: .
    ports:
      - "5279:80"
    environment:
      Connection_Strings_DefaultConnection: "Host=cargo_db; Port=5432; Database=postgres; Username=postgres; Password=postgres"
    depends_on:
      cargo_db:
        condition: service_healthy
    networks:
      - net

volumes:
  pgdata: { }